In [7]:
# import torch 
from torch import nn
import torch
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from scipy.stats import skew
from scipy.stats import kurtosis
from prettytable import PrettyTable
import os
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("Cuda Device Available")
    print("Name of the Cuda Device: ", torch.cuda.get_device_name())
    print("GPU Computational Capablity: ", torch.cuda.get_device_capability())

else:
    device = torch.device("cpu")
    
def changeCourtToValue(court):
    if court == 'Hard':
        return 1
    elif court == 'Clay':
        return 2
    elif court == 'Grass':
        return 3
    elif court == 'Carpet':
        return 4
    
def changeHandToValue(hand):
    if hand == 'R':
        return 1
    elif hand == 'U':
        return 0
    elif hand == 'L':
        return -1

    
    
def BuildDataset():
    df = pd.read_csv("data/atp_matches_2015.csv")
    for i in range(2016, 2023):
        newDf = pd.read_csv("data/atp_matches_" + str(i) + ".csv")
        df = pd.concat([df, newDf], join="inner", ignore_index = True)
    
    df = df[['surface', 'winner_hand', 'winner_ht', 'winner_age', 'winner_rank', 'winner_rank_points', 'loser_hand', 'loser_ht', 'loser_age', 'loser_rank', 'loser_rank_points']]
    
    
    avgSwitches = ['winner_ht', 'winner_age', 'loser_ht', 'loser_age']
    for i in avgSwitches:
        mean = df[i].mean()
        df[i] = df[i].fillna(mean)
        
    maxSwitches = ['winner_rank', 'loser_rank']
    for i in maxSwitches:
        Max = df[i].max()
        df[i] = df[i].fillna(Max)
    
    minSwitches = ['winner_rank_points', 'loser_rank_points']
    for i in minSwitches:
        df[i] = df[i].fillna(1)
        
    hands = ['winner_hand', 'loser_hand']
    for i in hands:
        df[i] = df[i].fillna('R')
    
    df['surface'] = df['surface'].apply(changeCourtToValue)
    df['winner_hand'] = df['winner_hand'].apply(changeHandToValue)
    df['loser_hand'] = df['loser_hand'].apply(changeHandToValue)
    df['Player1Wins'] = 1
    
    df.rename(columns = {'winner_hand': 'P1Hand', 'winner_ht': 'P1Height', 
                        'winner_age':'P1Age', 'winner_rank':'P1Rank', 'winner_rank_points': 'P1RankPoint',
                         'loser_hand': 'P2Hand', 'loser_ht': 'P2Height', 
                        'loser_age':'P2Age', 'loser_rank':'P2Rank', 'loser_rank_points': 'P2RankPoint'
                        }, inplace = True)
    
    for i in range(19622):
        if (i%2 == 0):
            df = swapPlayers(df, i)
    return df

def swapPlayers(df, index):
    df.loc[index, 'P1Hand'], df.loc[index, 'P2Hand'] = df.loc[index, 'P2Hand'], df.loc[index, 'P1Hand']
    df.loc[index, 'P1Height'], df.loc[index, 'P2Height'] = df.loc[index, 'P2Height'], df.loc[index, 'P1Height']
    df.loc[index, 'P1Age'], df.loc[index, 'P2Age'] = df.loc[index, 'P2Age'], df.loc[index, 'P1Age']
    df.loc[index, 'P1Rank'], df.loc[index, 'P2Rank'] = df.loc[index, 'P2Rank'], df.loc[index, 'P1Rank']
    df.loc[index, 'P1RankPoint'], df.loc[index, 'P2RankPoint'] = df.loc[index, 'P2RankPoint'], df.loc[index, 'P1RankPoint']
    df.loc[index, 'Player1Wins'] = 0
    return df

class NeuralNet(nn.Module):
    def __init__(self):
        super(NeuralNet, self).__init__()
        self.ff1 = nn.Linear(11, 32)
        self.ff2 = nn.Linear(32, 64)
        self.ff3 = nn.Linear(64, 32)
        self.ff4 = nn.Linear(32, 16)
        self.ff5 = nn.Linear(16, 4)
        self.ff6 = nn.Linear(4, 1)

    def forward(self, x):
        x = F.normalize(x)
        print(x, "\n")
        x = F.relu(self.ff1(x))
        print(x, "\n")
        x = F.relu(self.ff2(x))
        print(x, "\n")
        x = F.relu(self.ff3(x))
        print(x, "\n")
        x = F.relu(self.ff4(x))
        print(x, "\n")
        x = F.relu(self.ff5(x))
        print(x, "\n")
        x = torch.sigmoid(self.ff6(x))
        print(x, "\n")
        return x
    
def Train(model, X_train, y_train, epochs, learningRate, batchSize):
    
    criterion = nn.BCELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)
    
    dataset = torch.utils.data.TensorDataset(X_train, y_train)
    dataLoader = torch.utils.data.DataLoader(dataset=dataset, batch_size=batchSize, shuffle=True)
    
    for epoch in range(epochs):
        for i, (data, label) in enumerate(dataLoader):
         #   data = data
            label = label.type(torch.LongTensor)

            output = model(data)
            output = output.squeeze(1)
            output = output.float()
            label = label.float()
            print(output)
            print(label)
            output = torch.nan_to_num(output, nan=0.5)
            loss = criterion(output, label)
            print(loss)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            #Need Validation
            
        print("Epoch: " + str(epoch) + " Loss: " + str(loss.item()))

    print('Training Complete')
    
    

def main():
    df = BuildDataset()
    print(df.tail())
    
#main()
df = BuildDataset()
M = NeuralNet()
train, test = train_test_split(df, test_size=0.33)
X_train, y_train = torch.tensor(np.array(train.iloc[:, 0:-1])), torch.tensor(np.array(train.iloc[:, -1]))
X_test, y_test = torch.tensor(np.array(test.iloc[:, 0:-1])), torch.tensor(np.array(test.iloc[:, -1]))
X_train, y_train = X_train.float(), y_train.float()
print(X_train[0])
print(y_train[0])

Train(M, X_train, y_train, 20, 0.001, 3)

Cuda Device Available
Name of the Cuda Device:  NVIDIA GeForce RTX 3060 Laptop GPU
GPU Computational Capablity:  (8, 6)
tensor([1.0000e+00, 1.0000e+00, 1.9300e+02, 2.2973e+01, 2.0000e+01, 1.5850e+03,
        1.0000e+00, 1.8500e+02, 2.9317e+01, 1.1000e+01, 2.4000e+03])
tensor(1.)
tensor([[ 1.2829e-03, -6.4143e-04,  1.2380e-01,  2.2459e-02,  2.2450e-02,
          8.2745e-01,  6.4143e-04,  1.1610e-01,  1.8487e-02,  4.1693e-02,
          5.3239e-01],
        [ 6.7984e-04, -6.7984e-04,  1.2917e-01,  2.1243e-02,  2.9913e-02,
          9.0215e-01,  6.7984e-04,  1.2708e-01,  1.9307e-02,  3.8751e-01,
          3.7391e-02],
        [ 7.6358e-04,  7.6358e-04,  1.4508e-01,  2.5212e-02,  5.5741e-02,
          5.3451e-01, -7.6358e-04,  1.4355e-01,  2.5417e-02,  2.6725e-02,
          8.1703e-01]]) 

tensor([[0.3023, 0.0126, 0.4840, 0.1402, 0.0124, 0.0000, 0.0000, 0.0223, 0.2960,
         0.1696, 0.0000, 0.0702, 0.5808, 0.1046, 0.0000, 0.0792, 0.1336, 0.0000,
         0.2497, 0.0000, 0.0000, 0.0000, 0

tensor([[0.0087, 0.0000, 0.0292, 0.0000, 0.0000, 0.0824, 0.0000, 0.1135, 0.2028,
         0.0819, 0.0000, 0.0485, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2057,
         0.0000, 0.0000, 0.0098, 0.0350, 0.0000, 0.0081, 0.0986, 0.0000, 0.0296,
         0.0000, 0.0000, 0.0712, 0.0000, 0.0825],
        [0.0176, 0.0000, 0.0457, 0.0000, 0.0000, 0.0816, 0.0000, 0.0765, 0.1889,
         0.0826, 0.0000, 0.0692, 0.0000, 0.0000, 0.0000, 0.0000, 0.0009, 0.1757,
         0.0000, 0.0087, 0.0191, 0.0355, 0.0000, 0.0206, 0.0935, 0.0000, 0.0443,
         0.0000, 0.0000, 0.0520, 0.0000, 0.0817],
        [0.0116, 0.0000, 0.0328, 0.0000, 0.0000, 0.0846, 0.0000, 0.0972, 0.1965,
         0.0838, 0.0000, 0.0642, 0.0000, 0.0000, 0.0000, 0.0000, 0.0024, 0.1905,
         0.0000, 0.0030, 0.0139, 0.0370, 0.0000, 0.0148, 0.0970, 0.0000, 0.0307,
         0.0000, 0.0000, 0.0639, 0.0000, 0.0815]], grad_fn=<ReluBackward0>) 

tensor([[0.1029, 0.0000, 0.0964, 0.0000, 0.0000, 0.1399, 0.1046, 0.0685, 0.0000,
         0.0

tensor([[0.1038, 0.0000, 0.0949, 0.0000, 0.0000, 0.1231, 0.1180, 0.0656, 0.0000,
         0.0000, 0.0994, 0.0038, 0.0579, 0.0906, 0.0000, 0.0000],
        [0.1040, 0.0000, 0.0948, 0.0000, 0.0000, 0.1382, 0.1052, 0.0689, 0.0000,
         0.0000, 0.0908, 0.0000, 0.0423, 0.0940, 0.0000, 0.0000],
        [0.1363, 0.0000, 0.0694, 0.0000, 0.0000, 0.1190, 0.1463, 0.0712, 0.0000,
         0.0000, 0.0971, 0.0070, 0.0790, 0.0695, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>) 

tensor([[0.2511, 0.0550, 0.0000, 0.1195],
        [0.2491, 0.0526, 0.0000, 0.1211],
        [0.2472, 0.0598, 0.0000, 0.1254]], grad_fn=<ReluBackward0>) 

tensor([[0.5544],
        [0.5541],
        [0.5552]], grad_fn=<SigmoidBackward0>) 

tensor([0.5544, 0.5541, 0.5552], grad_fn=<SqueezeBackward1>)
tensor([1., 0., 1.])
tensor(0.6620, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[1.8372e-04, 9.1858e-05, 1.7269e-02, 3.0604e-03, 9.1858e-05, 9.9758e-01,
         9.1858e-05, 1.6994e-02, 2.5489e-03, 7.9917e-03, 6.4576e-02]

tensor([[0.3463, 0.0000, 0.4945, 0.1414, 0.0000, 0.0000, 0.0000, 0.0535, 0.2971,
         0.1738, 0.0000, 0.0969, 0.5710, 0.0707, 0.0000, 0.0411, 0.1101, 0.0000,
         0.2037, 0.0000, 0.0000, 0.0000, 0.1561, 0.0408, 0.1764, 0.4356, 0.5381,
         0.0000, 0.3361, 0.4284, 0.0000, 0.0320],
        [0.1757, 0.0402, 0.3852, 0.1529, 0.1244, 0.0000, 0.0000, 0.0446, 0.2776,
         0.1170, 0.0000, 0.0000, 0.5485, 0.1514, 0.0000, 0.1823, 0.2192, 0.0000,
         0.3412, 0.0000, 0.0000, 0.0000, 0.0594, 0.0034, 0.1153, 0.3392, 0.4592,
         0.0000, 0.3083, 0.3976, 0.0000, 0.0187],
        [0.2337, 0.0380, 0.4122, 0.1432, 0.0732, 0.0000, 0.0000, 0.0793, 0.2963,
         0.1433, 0.0000, 0.0000, 0.5605, 0.1063, 0.0000, 0.1254, 0.1818, 0.0000,
         0.2993, 0.0000, 0.0000, 0.0000, 0.1042, 0.0133, 0.1528, 0.3785, 0.4885,
         0.0000, 0.3341, 0.4078, 0.0000, 0.0460]], grad_fn=<ReluBackward0>) 

tensor([[0.0000, 0.0212, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1587, 0.1057,
         0.0

tensor([[0.0000e+00, 2.2386e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.7468e-04,
         0.0000e+00, 1.5626e-01, 1.0667e-01, 0.0000e+00, 0.0000e+00, 1.7108e-01,
         2.3225e-01, 0.0000e+00, 1.8014e-01, 0.0000e+00, 1.2131e-01, 7.0172e-02,
         1.7287e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.6126e-02, 4.1346e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 4.6260e-02, 1.1132e-01, 2.1589e-01,
         2.0071e-01, 0.0000e+00, 2.1272e-01, 0.0000e+00, 0.0000e+00, 1.5182e-01,
         0.0000e+00, 1.6135e-01, 4.7893e-02, 1.8598e-01, 0.0000e+00, 4.3958e-02,
         0.0000e+00, 1.3026e-01, 9.5379e-02, 1.0054e-01, 1.5845e-01, 4.9727e-02,
         0.0000e+00, 0.0000e+00, 1.5314e-01, 1.3602e-01, 2.5540e-01, 0.0000e+00,
         7.8204e-02, 3.2350e-01, 1.0091e-01, 1.9080e-01, 0.0000e+00, 3.9011e-02,
         0.0000e+00, 0.0000e+00, 5.0940e-02, 2.5029e-01],
        [0.0000e+00, 4.0596e-02, 0.0000e+00, 0.0000e+00, 4.4632e-03, 1.9862e-02,
         0.0000e+00, 1.2589e-01, 1.0506e-01, 0.0000

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0233, 0.0000, 0.0440, 0.2330, 0.0439,
         0.0000, 0.0000, 0.2286, 0.1211, 0.0296, 0.0608, 0.0000, 0.0343, 0.1731,
         0.1011, 0.0721, 0.0000, 0.0000, 0.0092, 0.0268, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0625, 0.2154, 0.1990, 0.0000, 0.0565, 0.0000, 0.0000, 0.0692,
         0.0000, 0.0707, 0.0922, 0.0879, 0.0000, 0.0211, 0.0000, 0.1903, 0.0248,
         0.2625, 0.1051, 0.0000, 0.0000, 0.0077, 0.2187, 0.0561, 0.1317, 0.0000,
         0.1571, 0.1965, 0.0187, 0.2410, 0.0119, 0.0000, 0.0000, 0.0000, 0.0000,
         0.3025],
        [0.0000, 0.0591, 0.0000, 0.0000, 0.0322, 0.0197, 0.0000, 0.0874, 0.0990,
         0.0000, 0.0000, 0.1802, 0.1277, 0.0390, 0.2262, 0.0000, 0.1282, 0.0911,
         0.1482, 0.0000, 0.0000, 0.0000, 0.0411, 0.0353, 0.0000, 0.0000, 0.0000,
         0.0643, 0.1096, 0.1807, 0.2057, 0.0000, 0.1359, 0.0000, 0.0000, 0.1485,
         0.0000, 0.1299, 0.0252, 0.1776, 0.0000, 0.0651, 0.0000, 0.1022, 0.0297,
         0

tensor([[0.4571, 0.0000, 0.5117, 0.1564, 0.0000, 0.0000, 0.0000, 0.0766, 0.2616,
         0.1432, 0.0000, 0.1899, 0.5068, 0.0000, 0.0000, 0.0000, 0.0531, 0.0000,
         0.0685, 0.0000, 0.0000, 0.0000, 0.1826, 0.1152, 0.1786, 0.4475, 0.5136,
         0.0000, 0.3506, 0.4076, 0.0924, 0.0000],
        [0.2081, 0.0320, 0.4213, 0.1653, 0.0991, 0.0000, 0.0000, 0.0000, 0.2845,
         0.1205, 0.0000, 0.0095, 0.5687, 0.1592, 0.0000, 0.1746, 0.1912, 0.0000,
         0.3290, 0.0000, 0.0000, 0.0000, 0.0587, 0.0092, 0.1086, 0.3600, 0.4774,
         0.0000, 0.2839, 0.4152, 0.0000, 0.0007],
        [0.4993, 0.0000, 0.4512, 0.1863, 0.0000, 0.0000, 0.0000, 0.1283, 0.2086,
         0.0689, 0.0000, 0.2227, 0.4138, 0.0000, 0.0000, 0.0000, 0.0449, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0910, 0.1696, 0.1761, 0.1501, 0.4142, 0.4323,
         0.0000, 0.3626, 0.3734, 0.1894, 0.0000]], grad_fn=<ReluBackward0>) 

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1729, 0.0954,
         0.0

tensor([[0.0269, 0.0000, 0.0471, 0.0000, 0.0000, 0.0731, 0.0000, 0.0922, 0.1874,
         0.0791, 0.0000, 0.0473, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1929,
         0.0000, 0.0010, 0.0129, 0.0291, 0.0000, 0.0093, 0.0921, 0.0000, 0.0558,
         0.0000, 0.0000, 0.0520, 0.0000, 0.0779],
        [0.0149, 0.0000, 0.0434, 0.0000, 0.0000, 0.0895, 0.0000, 0.0769, 0.1862,
         0.0855, 0.0000, 0.0765, 0.0000, 0.0000, 0.0000, 0.0000, 0.0049, 0.1746,
         0.0000, 0.0116, 0.0220, 0.0365, 0.0000, 0.0196, 0.0910, 0.0000, 0.0360,
         0.0000, 0.0000, 0.0535, 0.0000, 0.0812],
        [0.0246, 0.0000, 0.0628, 0.0000, 0.0000, 0.1002, 0.0000, 0.0483, 0.1566,
         0.0890, 0.0003, 0.0974, 0.0000, 0.0000, 0.0000, 0.0000, 0.0064, 0.1451,
         0.0000, 0.0238, 0.0381, 0.0278, 0.0000, 0.0185, 0.0726, 0.0000, 0.0462,
         0.0000, 0.0000, 0.0330, 0.0000, 0.0762]], grad_fn=<ReluBackward0>) 

tensor([[0.1070, 0.0000, 0.0906, 0.0000, 0.0000, 0.1329, 0.1088, 0.0702, 0.0000,
         0.0

tensor([[0.5497],
        [0.5496],
        [0.5496]], grad_fn=<SigmoidBackward0>) 

tensor([0.5497, 0.5496, 0.5496], grad_fn=<SqueezeBackward1>)
tensor([0., 0., 1.])
tensor(0.7313, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[6.5711e-04, 3.2856e-04, 5.9140e-02, 9.0134e-03, 3.2856e-03, 9.6267e-01,
         3.2856e-04, 6.0783e-02, 8.4170e-03, 2.3985e-02, 2.5562e-01],
        [1.0216e-03, 1.0216e-03, 1.9716e-01, 2.1357e-02, 6.3337e-02, 8.4279e-01,
         1.0216e-03, 1.9096e-01, 1.7497e-02, 4.4949e-01, 8.6833e-02],
        [1.8186e-03, 1.8186e-03, 3.3996e-01, 4.1780e-02, 4.9285e-01, 3.7100e-01,
         0.0000e+00, 3.4119e-01, 4.8218e-02, 5.2558e-01, 3.2735e-01]]) 

tensor([[0.2010, 0.0348, 0.4109, 0.1534, 0.1048, 0.0000, 0.0000, 0.0277, 0.2836,
         0.1287, 0.0000, 0.0000, 0.5621, 0.1487, 0.0000, 0.1631, 0.2006, 0.0000,
         0.3270, 0.0000, 0.0000, 0.0000, 0.0713, 0.0040, 0.1214, 0.3578, 0.4778,
         0.0000, 0.3043, 0.4094, 0.0000, 0.0178],
        [0.2432, 0.0374, 0.380

tensor([0.5496, 0.5496, 0.5497], grad_fn=<SqueezeBackward1>)
tensor([0., 1., 1.])
tensor(0.6649, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[1.3081e-03, 6.5405e-04, 1.2296e-01, 1.8168e-02, 1.8967e-02, 8.2672e-01,
         6.5405e-04, 1.2100e-01, 2.0213e-02, 3.9243e-02, 5.3305e-01],
        [1.8619e-04, 1.8619e-04, 3.5004e-02, 6.0030e-03, 5.7719e-03, 2.2157e-01,
         1.8619e-04, 3.6494e-02, 5.5768e-03, 1.1171e-03, 9.7378e-01],
        [1.6286e-04, 1.6286e-04, 3.2246e-02, 3.8957e-03, 1.1400e-03, 9.8855e-01,
         1.6286e-04, 3.0617e-02, 3.5782e-03, 1.3517e-02, 1.4348e-01]]) 

tensor([[0.3033, 0.0093, 0.4857, 0.1428, 0.0131, 0.0000, 0.0000, 0.0211, 0.2972,
         0.1693, 0.0000, 0.0715, 0.5817, 0.1065, 0.0000, 0.0782, 0.1334, 0.0000,
         0.2489, 0.0000, 0.0000, 0.0000, 0.1284, 0.0232, 0.1576, 0.4186, 0.5333,
         0.0000, 0.3159, 0.4303, 0.0000, 0.0251],
        [0.4712, 0.0000, 0.4681, 0.1706, 0.0000, 0.0000, 0.0000, 0.1236, 0.2396,
         0.1066, 0.0000, 0.1948, 0

tensor([[0.2437, 0.0427, 0.0000, 0.1149],
        [0.2465, 0.0470, 0.0000, 0.1148],
        [0.2472, 0.0479, 0.0000, 0.1154]], grad_fn=<ReluBackward0>) 

tensor([[0.5481],
        [0.5488],
        [0.5490]], grad_fn=<SigmoidBackward0>) 

tensor([0.5481, 0.5488, 0.5490], grad_fn=<SqueezeBackward1>)
tensor([1., 1., 0.])
tensor(0.6659, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[5.9525e-05, 5.9525e-05, 1.1012e-02, 1.9102e-03, 7.2026e-03, 2.8929e-02,
         5.9525e-05, 1.1191e-02, 1.7117e-03, 5.9525e-05, 9.9943e-01],
        [6.4451e-04, 3.2226e-04, 6.2195e-02, 1.0116e-02, 3.9637e-02, 1.4759e-01,
         3.2226e-04, 5.8006e-02, 8.5317e-03, 3.8671e-03, 9.8449e-01],
        [1.6666e-04, 1.6666e-04, 3.1331e-02, 3.8569e-03, 4.6664e-03, 2.3582e-01,
         1.6666e-04, 3.0831e-02, 4.3899e-03, 6.6663e-04, 9.7077e-01]]) 

tensor([[0.4995, 0.0000, 0.4438, 0.1893, 0.0000, 0.0000, 0.0000, 0.1341, 0.2053,
         0.0625, 0.0000, 0.2226, 0.4078, 0.0000, 0.0000, 0.0000, 0.0464, 0.0000,
       

tensor([[0.3662, 0.0000, 0.4905, 0.1401, 0.0000, 0.0000, 0.0000, 0.0753, 0.2927,
         0.1702, 0.0000, 0.1084, 0.5577, 0.0478, 0.0000, 0.0276, 0.1012, 0.0000,
         0.1804, 0.0000, 0.0000, 0.0000, 0.1659, 0.0520, 0.1825, 0.4395, 0.5329,
         0.0000, 0.3464, 0.4247, 0.0000, 0.0338],
        [0.3288, 0.0000, 0.5276, 0.1589, 0.0000, 0.0000, 0.0000, 0.0000, 0.3041,
         0.1597, 0.0000, 0.1291, 0.5982, 0.1198, 0.0000, 0.0883, 0.1023, 0.0000,
         0.2374, 0.0000, 0.0000, 0.0000, 0.0990, 0.0508, 0.1375, 0.4185, 0.5388,
         0.0000, 0.2631, 0.4319, 0.0000, 0.0000],
        [0.3530, 0.0000, 0.3070, 0.4019, 0.0000, 0.0000, 0.0000, 0.0000, 0.2564,
         0.0000, 0.0802, 0.3514, 0.4056, 0.0229, 0.2097, 0.4318, 0.0540, 0.1416,
         0.2256, 0.0000, 0.0000, 0.0000, 0.0000, 0.3162, 0.0000, 0.2700, 0.1959,
         0.0571, 0.0533, 0.3203, 0.0000, 0.0000]], grad_fn=<ReluBackward0>) 

tensor([[0.0000, 0.0179, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1628, 0.1031,
         0.0

tensor([[0.3268, 0.0035, 0.5147, 0.1477, 0.0000, 0.0000, 0.0000, 0.0000, 0.2999,
         0.1676, 0.0000, 0.1112, 0.5904, 0.1098, 0.0000, 0.0793, 0.1095, 0.0000,
         0.2367, 0.0000, 0.0000, 0.0000, 0.1147, 0.0396, 0.1472, 0.4221, 0.5407,
         0.0000, 0.2829, 0.4330, 0.0000, 0.0000],
        [0.2874, 0.0140, 0.4798, 0.1477, 0.0309, 0.0000, 0.0000, 0.0056, 0.2975,
         0.1627, 0.0000, 0.0627, 0.5844, 0.1213, 0.0000, 0.0958, 0.1409, 0.0000,
         0.2653, 0.0000, 0.0000, 0.0000, 0.1158, 0.0194, 0.1487, 0.4100, 0.5278,
         0.0000, 0.3062, 0.4290, 0.0000, 0.0194],
        [0.3356, 0.0000, 0.5081, 0.1421, 0.0000, 0.0000, 0.0000, 0.0111, 0.2981,
         0.1750, 0.0000, 0.1029, 0.5818, 0.0914, 0.0000, 0.0563, 0.1123, 0.0000,
         0.2204, 0.0000, 0.0000, 0.0000, 0.1383, 0.0369, 0.1629, 0.4322, 0.5437,
         0.0000, 0.3143, 0.4323, 0.0000, 0.0171]], grad_fn=<ReluBackward0>) 

tensor([[0.0000, 0.0201, 0.0000, 0.0000, 0.0074, 0.0000, 0.0000, 0.1543, 0.1090,
         0.0


tensor([[0.0141, 0.0000, 0.0347, 0.0000, 0.0000, 0.0859, 0.0000, 0.0926, 0.1941,
         0.0850, 0.0000, 0.0683, 0.0000, 0.0000, 0.0000, 0.0000, 0.0034, 0.1865,
         0.0000, 0.0046, 0.0148, 0.0353, 0.0000, 0.0174, 0.0991, 0.0000, 0.0322,
         0.0000, 0.0000, 0.0616, 0.0000, 0.0805],
        [0.0157, 0.0000, 0.0425, 0.0000, 0.0000, 0.0951, 0.0000, 0.0764, 0.1797,
         0.0880, 0.0000, 0.0833, 0.0000, 0.0000, 0.0000, 0.0000, 0.0077, 0.1706,
         0.0000, 0.0132, 0.0233, 0.0342, 0.0000, 0.0192, 0.0887, 0.0000, 0.0332,
         0.0000, 0.0000, 0.0524, 0.0000, 0.0802],
        [0.0260, 0.0000, 0.0462, 0.0000, 0.0000, 0.1123, 0.0000, 0.0701, 0.1430,
         0.0916, 0.0000, 0.1036, 0.0000, 0.0000, 0.0000, 0.0000, 0.0181, 0.1495,
         0.0000, 0.0220, 0.0233, 0.0247, 0.0000, 0.0189, 0.0718, 0.0000, 0.0333,
         0.0000, 0.0000, 0.0413, 0.0000, 0.0748]], grad_fn=<ReluBackward0>) 

tensor([[0.1017, 0.0000, 0.0980, 0.0000, 0.0000, 0.1288, 0.1047, 0.0638, 0.0000,
         0.

tensor([[0.0000e+00, 4.1736e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.1023e-02,
         0.0000e+00, 1.3641e-01, 1.0632e-01, 0.0000e+00, 0.0000e+00, 1.5864e-01,
         2.1248e-01, 4.2566e-03, 1.9943e-01, 0.0000e+00, 1.2416e-01, 5.3633e-02,
         1.7841e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.7195e-02, 2.6789e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 6.3638e-02, 1.0085e-01, 2.0184e-01,
         1.8423e-01, 0.0000e+00, 1.8534e-01, 0.0000e+00, 0.0000e+00, 1.4169e-01,
         0.0000e+00, 1.7028e-01, 4.1126e-02, 1.7141e-01, 0.0000e+00, 5.0304e-02,
         0.0000e+00, 1.2777e-01, 9.1574e-02, 1.0519e-01, 1.5508e-01, 3.7073e-02,
         0.0000e+00, 0.0000e+00, 1.5980e-01, 1.1125e-01, 2.3608e-01, 0.0000e+00,
         6.7791e-02, 3.2170e-01, 8.9182e-02, 1.6497e-01, 0.0000e+00, 5.4863e-02,
         0.0000e+00, 0.0000e+00, 7.3108e-02, 2.3818e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 1.8048e-01, 1.0127e-01, 0.0000

tensor([0.5435, 0.5433, 0.5440], grad_fn=<SqueezeBackward1>)
tensor([0., 0., 0.])
tensor(0.7844, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[ 2.8282e-03,  9.4272e-04,  1.7252e-01,  2.7385e-02,  5.2792e-02,
          8.7767e-01,  9.4272e-04,  1.7440e-01,  2.5018e-02,  1.2915e-01,
          3.8557e-01],
        [ 9.0732e-04,  9.0732e-04,  1.6332e-01,  2.1021e-02,  8.8010e-02,
          6.9683e-01,  9.0732e-04,  1.6332e-01,  2.8461e-02,  9.2547e-02,
          6.6598e-01],
        [ 6.6007e-04, -3.3004e-04,  6.2047e-02,  7.5061e-03,  3.3664e-02,
          1.9769e-01,  3.3004e-04,  6.7987e-02,  1.0914e-02,  3.3004e-03,
          9.7526e-01]]) 

tensor([[0.2800, 0.0156, 0.4850, 0.1632, 0.0304, 0.0000, 0.0000, 0.0000, 0.3000,
         0.1455, 0.0000, 0.0826, 0.5912, 0.1357, 0.0000, 0.1253, 0.1376, 0.0000,
         0.2809, 0.0000, 0.0000, 0.0000, 0.0833, 0.0289, 0.1248, 0.4009, 0.5172,
         0.0000, 0.2712, 0.4303, 0.0000, 0.0000],
        [0.3709, 0.0000, 0.5313, 0.1445, 0.0000, 0.0000

tensor([[0.0154, 0.0000, 0.0372, 0.0000, 0.0000, 0.0904, 0.0000, 0.0862, 0.1879,
         0.0860, 0.0000, 0.0738, 0.0000, 0.0000, 0.0000, 0.0000, 0.0051, 0.1805,
         0.0000, 0.0083, 0.0177, 0.0353, 0.0000, 0.0191, 0.0944, 0.0000, 0.0320,
         0.0000, 0.0000, 0.0590, 0.0000, 0.0811],
        [0.0214, 0.0000, 0.0536, 0.0000, 0.0000, 0.0955, 0.0000, 0.0620, 0.1719,
         0.0897, 0.0000, 0.0885, 0.0000, 0.0000, 0.0000, 0.0000, 0.0076, 0.1602,
         0.0000, 0.0191, 0.0295, 0.0334, 0.0000, 0.0208, 0.0845, 0.0000, 0.0390,
         0.0000, 0.0000, 0.0451, 0.0000, 0.0795],
        [0.0111, 0.0000, 0.0279, 0.0000, 0.0000, 0.0850, 0.0000, 0.1105, 0.2009,
         0.0856, 0.0000, 0.0568, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2014,
         0.0000, 0.0000, 0.0100, 0.0332, 0.0000, 0.0116, 0.1016, 0.0000, 0.0271,
         0.0000, 0.0000, 0.0702, 0.0000, 0.0835]], grad_fn=<ReluBackward0>) 

tensor([[0.1023, 0.0000, 0.0979, 0.0000, 0.0000, 0.1258, 0.1055, 0.0628, 0.0000,
         0.0

tensor([[0.0216, 0.0000, 0.0404, 0.0000, 0.0000, 0.0783, 0.0000, 0.1098, 0.1972,
         0.0777, 0.0000, 0.0364, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2090,
         0.0000, 0.0000, 0.0107, 0.0297, 0.0000, 0.0033, 0.0953, 0.0000, 0.0419,
         0.0000, 0.0000, 0.0644, 0.0000, 0.0804],
        [0.0230, 0.0000, 0.0415, 0.0000, 0.0000, 0.0771, 0.0000, 0.0945, 0.1901,
         0.0817, 0.0000, 0.0525, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1921,
         0.0000, 0.0000, 0.0133, 0.0288, 0.0000, 0.0134, 0.0972, 0.0000, 0.0487,
         0.0000, 0.0000, 0.0563, 0.0000, 0.0812],
        [0.0178, 0.0000, 0.0377, 0.0000, 0.0000, 0.0808, 0.0000, 0.0909, 0.1903,
         0.0835, 0.0000, 0.0618, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1868,
         0.0000, 0.0003, 0.0152, 0.0305, 0.0000, 0.0166, 0.0997, 0.0000, 0.0439,
         0.0000, 0.0000, 0.0576, 0.0000, 0.0836]], grad_fn=<ReluBackward0>) 

tensor([[0.1075, 0.0000, 0.0947, 0.0000, 0.0000, 0.1347, 0.1011, 0.0683, 0.0000,
         0.0

tensor([[0.0000e+00, 4.9669e-02, 0.0000e+00, 0.0000e+00, 2.0466e-02, 2.0278e-02,
         0.0000e+00, 1.0465e-01, 1.0125e-01, 0.0000e+00, 0.0000e+00, 1.7618e-01,
         1.5884e-01, 2.3928e-02, 2.1403e-01, 0.0000e+00, 1.2913e-01, 8.4713e-02,
         1.5236e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.0717e-02, 3.8778e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 6.2640e-02, 1.1193e-01, 1.9165e-01,
         2.0444e-01, 0.0000e+00, 1.6009e-01, 0.0000e+00, 0.0000e+00, 1.5302e-01,
         0.0000e+00, 1.3695e-01, 3.1848e-02, 1.8292e-01, 0.0000e+00, 6.1350e-02,
         0.0000e+00, 1.0862e-01, 4.9185e-02, 1.0073e-01, 1.7607e-01, 3.4608e-02,
         0.0000e+00, 1.5010e-02, 1.8916e-01, 1.5306e-01, 2.5236e-01, 0.0000e+00,
         7.1715e-02, 2.9980e-01, 5.1303e-02, 1.8855e-01, 0.0000e+00, 3.8229e-02,
         0.0000e+00, 0.0000e+00, 9.7262e-02, 2.3030e-01],
        [0.0000e+00, 2.1989e-02, 0.0000e+00, 0.0000e+00, 2.8886e-04, 6.0732e-04,
         0.0000e+00, 1.5175e-01, 1.0647e-01, 0.0000

KeyboardInterrupt: 

In [ ]:
df.isna().sum()